import { Inter } from "next/font/google";
import "./globals.css";
import ThemeClient from "./themeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}><ThemeClient>{children}</ThemeClient></body>
    </html>
  );
}
